import CloudinaryImage from '@/components/CloudinaryImage'

export default function TestMyImage() {
  // Your uploaded Cloudinary public ID
  const myImagePublicId = 'v1766005149/River_rhvmae'

  return (
    <div style={{ padding: '40px', background: '#f5f5f5', minHeight: '100vh' }}>
      <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
        <h1 style={{ textAlign: 'center', marginBottom: '40px' }}>
          🎉 Your Uploaded Cloudinary Image
        </h1>

        <div style={{
          background: '#fff',
          padding: '40px',
          borderRadius: '8px',
          boxShadow: '0 4px 12px rgba(0,0,0,0.1)'
        }}>
          <h2 style={{ marginTop: 0 }}>Your Image:</h2>

          {/* Display the uploaded image */}
          <div style={{ textAlign: 'center', marginBottom: '30px' }}>
            <CloudinaryImage
              publicId={myImagePublicId}
              alt="River Photo"
              width={800}
              height={600}
              size="full"
              style={{
                borderRadius: '8px',
                boxShadow: '0 4px 12px rgba(0,0,0,0.2)'
              }}
            />
          </div>

          {/* Image Details */}
          <div style={{
            padding: '20px',
            background: '#f0f9ff',
            borderRadius: '4px',
            marginBottom: '20px'
          }}>
            <h3 style={{ marginTop: 0 }}>📊 Image Details:</h3>
            <p><strong>Public ID:</strong> <code>{myImagePublicId}</code></p>
            <p><strong>Cloud Name:</strong> dx0xikqmq</p>
            <p><strong>Format:</strong> Automatic (WebP/JPEG)</p>
            <p><strong>CDN:</strong> Cloudinary Global CDN</p>
          </div>

          {/* Usage Examples */}
          <div style={{
            padding: '20px',
            background: '#f5f5f5',
            borderRadius: '4px',
            marginBottom: '20px'
          }}>
            <h3 style={{ marginTop: 0 }}>💻 How to Use in Your Code:</h3>

            <h4>1. Basic Usage:</h4>
            <pre style={{
              background: '#2d2d2d',
              color: '#f8f8f2',
              padding: '15px',
              borderRadius: '4px',
              overflow: 'auto'
            }}>
{`import CloudinaryImage from '@/components/CloudinaryImage'

<CloudinaryImage
  publicId="${myImagePublicId}"
  alt="River Photo"
  width={800}
  height={600}
  size="full"
/>`}
            </pre>

            <h4>2. Different Sizes:</h4>
            <pre style={{
              background: '#2d2d2d',
              color: '#f8f8f2',
              padding: '15px',
              borderRadius: '4px',
              overflow: 'auto'
            }}>
{`// Thumbnail (for listings)
<CloudinaryImage
  publicId="${myImagePublicId}"
  alt="River"
  width={280}
  height={210}
  size="thumbnail"
/>

// Grid (for galleries)
<CloudinaryImage
  publicId="${myImagePublicId}"
  alt="River"
  width={600}
  height={450}
  size="grid"
/>

// Lightbox (for full view)
<CloudinaryImage
  publicId="${myImagePublicId}"
  alt="River"
  width={1200}
  height={900}
  size="lightbox"
/>`}
            </pre>
          </div>

          {/* Instructions */}
          <div style={{
            padding: '20px',
            background: '#d1ecf1',
            borderLeft: '4px solid #0c5460',
            borderRadius: '4px'
          }}>
            <h3 style={{ marginTop: 0 }}>✅ Success! Cloudinary is Working</h3>
            <p style={{ fontSize: '16px', lineHeight: '1.6' }}>
              Your image is now:
            </p>
            <ul style={{ lineHeight: '1.8' }}>
              <li>✅ Stored on Cloudinary's global CDN</li>
              <li>✅ Automatically optimized (WebP format if supported)</li>
              <li>✅ Loading from the nearest server worldwide</li>
              <li>✅ Much smaller file size than original</li>
            </ul>

            <h4 style={{ marginTop: '20px' }}>🚀 Next Steps:</h4>
            <ol style={{ lineHeight: '1.8' }}>
              <li>Use this <strong>Public ID</strong> in your photo components</li>
              <li>Replace <code>publicId="sample"</code> with <code>publicId="{myImagePublicId}"</code></li>
              <li>Check the Network tab - you'll see WebP format and smaller file size!</li>
              <li>Upload more images and collect their Public IDs</li>
            </ol>
          </div>

          {/* Image URL Info */}
          <div style={{
            marginTop: '20px',
            padding: '15px',
            background: '#fff3cd',
            borderRadius: '4px'
          }}>
            <p style={{ margin: 0, fontSize: '14px' }}>
              <strong>💡 Note:</strong> The Public ID is <code>{myImagePublicId}</code>
              <br/>
              The full URL is automatically generated by CloudinaryImage component
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
